sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    #修改为环境变量获取
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: sky-take-out-zank1
  alipay:
    # 支付宝支付回调地址（内网穿透）
    notify-url: http://49906452.r11.cpolar.top/notify
  bcrypt:
    # bcrypt加密算法的盐值，盐值越大破解越难，验证也需要更久的时间，默认为12
    salt: 13
  wechat:
    appid: ${WX_APPID}
    secret: ${WX_APPSECRET}
  amap:
    api-key: ${AMAP_API_KEY}
  shop:
    address: 江西省南昌市红谷滩区丰和南大道696号20栋626
    name: 苍穹外卖
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 10